#!/bin/bash
DEVICE="Wacom Bamboo 2FG 6x8"
STYLUS="$DEVICE Pen stylus"
ERASER="$DEVICE Pen eraser"
PAD="$DEVICE Pad pad"
FINGER="$DEVICE Finger touch"
xsetwacom --set "$PAD" "Button" "1" "key ctrl"
xsetwacom --set "$PAD" "Button" "3" "button +6 "
xsetwacom --set "$PAD" "Button" "8" "button +7 "
xsetwacom --set "$PAD" "Button" "9" "button +8 "
xsetwacom --set "$STYLUS" "Button" "1" "button +1 "
xsetwacom --set "$STYLUS" "Button" "2" "key shift"
xsetwacom --set "$STYLUS" "Button" "3" "button +6 "
xsetwacom --set "$ERASER" "Button" "1" "button +1 "
xsetwacom --set "$ERASER" "Button" "2" "button +6 "
xsetwacom --set "$ERASER" "Button" "3" "key shift"
xsetwacom --set "$FINGER" "Touch" "off"
xsetwacom --set "$FINGER" "Gesture" "off"
