#!/bin/bash

## Background ##
#nitrogen --restore &
#sh ~/.fehbg &
xwinwrap -b -fs -nf -ni -ov -sp -- feh --bg-fill --randomize --no-fehbg ~/Images/Wallpaper &

## Compositor ##
compton &

## Panel ##
(sleep 1 && tint2) &
if [ "$DE" != "chrome" ]; then
    volctl &

    ## Applications ##
    mpd &
    dunst &
    urxvtd &
    tilda &
    dbus-launch thunar --daemon &
    #(sleep 3 && synergy) &
    sh ~/.conky/conky-startup.sh &
fi
## Remote Connection ##
#crd --start &
#tmux new-session -s ngrok -d ngrok tcp 22 --log false &

## Polkit ##
#/usr/lib/lxpolkit/lxpolkit &
